"""
engineer_agent.py
-----------------
The Engineer Agent - The Builder.
Reads the product spec, generates an HTML landing page,
creates a GitHub issue, commits the file, and opens a Pull Request.
"""

import os
import json
import re
import base64
import requests
from groq import Groq
from dotenv import load_dotenv
import message_bus as bus

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")
GITHUB_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}


def call_llm(system_prompt, user_prompt):
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.7,
        max_tokens=2000
    )
    return response.choices[0].message.content


def generate_html(idea, product_spec):
    """Use LLM to generate a complete HTML landing page."""
    print("\n[ENGINEER] Generating HTML landing page...")

    value_prop = product_spec.get("value_proposition", "")
    features = product_spec.get("features", [])
    features_text = "\n".join([f"- {f['name']}: {f['description']}" for f in features])

    system_prompt = """You are a skilled frontend developer. Generate a complete, beautiful HTML 
landing page. Respond with ONLY the raw HTML code, nothing else. No explanation, no markdown, 
no backticks. Start directly with <!DOCTYPE html>."""

    user_prompt = f"""Create a complete HTML landing page for this startup:

Startup idea: {idea}
Value proposition: {value_prop}
Features:
{features_text}

Requirements:
- Include a compelling headline and subheadline
- Include a features section showing all features
- Include a call-to-action button
- Include basic but beautiful inline CSS styling
- Use a modern, clean design with good colors
- Make it look professional and complete
- Author comment at top: <!-- Generated by EngineerAgent <agent@launchmind.ai> -->"""

    html = call_llm(system_prompt, user_prompt)
    html = html.strip()
    if html.startswith("```"):
        html = re.sub(r"```html?", "", html)
        html = html.replace("```", "").strip()

    print("[ENGINEER] HTML landing page generated successfully.")
    return html


def get_main_branch_sha():
    """Get the SHA of the main branch."""
    for branch in ["main", "master"]:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/git/refs/heads/{branch}"
        response = requests.get(url, headers=GITHUB_HEADERS)
        if response.status_code == 200:
            return response.json()["object"]["sha"], branch
    return None, "main"


def create_branch(branch_name, sha):
    """Create a new branch from the given SHA."""
    print(f"[ENGINEER] Creating branch: {branch_name}")
    url = f"https://api.github.com/repos/{GITHUB_REPO}/git/refs"
    response = requests.post(url, headers=GITHUB_HEADERS, json={
        "ref": f"refs/heads/{branch_name}",
        "sha": sha
    })
    if response.status_code == 201:
        print(f"[ENGINEER] Branch '{branch_name}' created successfully.")
    elif response.status_code == 422:
        print(f"[ENGINEER] Branch already exists, continuing...")
    else:
        print(f"[ENGINEER] Branch creation failed: {response.json()}")


def commit_file(branch_name, html_content, idea):
    """Commit the HTML file to the branch."""
    print(f"[ENGINEER] Committing index.html to branch '{branch_name}'...")
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/index.html"

    check = requests.get(url + f"?ref={branch_name}", headers=GITHUB_HEADERS)

    payload = {
        "message": f"Add landing page for {idea[:50]}",
        "content": base64.b64encode(html_content.encode()).decode(),
        "branch": branch_name,
        "author": {"name": "EngineerAgent", "email": "agent@launchmind.ai"}
    }

    if check.status_code == 200:
        payload["sha"] = check.json()["sha"]

    response = requests.put(url, headers=GITHUB_HEADERS, json=payload)
    if response.status_code in [200, 201]:
        print("[ENGINEER] File committed successfully.")
        return True
    else:
        print(f"[ENGINEER] Commit failed: {response.json()}")
        return False


def create_github_issue(idea, product_spec):
    """Create a GitHub issue for the landing page."""
    print("[ENGINEER] Creating GitHub issue...")
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"

    value_prop = product_spec.get("value_proposition", "")
    features = product_spec.get("features", [])
    features_list = "\n".join([f"- {f['name']}: {f['description']}" for f in features])

    body = f"""## Landing Page Task

**Startup Idea:** {idea}

**Value Proposition:** {value_prop}

**Features to implement:**
{features_list}

---
*This issue was automatically created by the EngineerAgent as part of the LaunchMind multi-agent system.*"""

    response = requests.post(url, headers=GITHUB_HEADERS, json={
        "title": "Initial landing page",
        "body": body
    })

    if response.status_code == 201:
        issue_url = response.json()["html_url"]
        print(f"[ENGINEER] GitHub issue created: {issue_url}")
        return issue_url
    else:
        print(f"[ENGINEER] Issue creation failed: {response.json()}")
        return None


def get_or_create_pull_request(branch_name, base_branch, idea, issue_url):
    """Open a PR or fetch the existing one."""
    print("[ENGINEER] Opening Pull Request...")

    # Check if PR already exists
    existing = requests.get(
        f"https://api.github.com/repos/{GITHUB_REPO}/pulls",
        headers=GITHUB_HEADERS,
        params={"head": f"{GITHUB_REPO.split('/')[0]}:{branch_name}", "state": "open"}
    )
    if existing.status_code == 200 and existing.json():
        pr_url = existing.json()[0]["html_url"]
        print(f"[ENGINEER] Existing PR found: {pr_url}")
        return pr_url

    # Create new PR
    body = f"""## Landing Page PR

This PR adds the initial HTML landing page for the startup:
**{idea}**

### Related Issue: {issue_url}

---
*Auto-created by EngineerAgent — LaunchMind multi-agent system.*"""

    response = requests.post(
        f"https://api.github.com/repos/{GITHUB_REPO}/pulls",
        headers=GITHUB_HEADERS,
        json={
            "title": "Initial landing page",
            "body": body,
            "head": branch_name,
            "base": base_branch
        }
    )

    if response.status_code == 201:
        pr_url = response.json()["html_url"]
        print(f"[ENGINEER] Pull Request created: {pr_url}")
        return pr_url
    else:
        print(f"[ENGINEER] PR creation failed: {response.json()}")
        return None


def run():
    """Main Engineer Agent function."""
    print("\n" + "-"*40)
    print("ENGINEER AGENT RUNNING")
    print("-"*40)

    messages = bus.receive("engineer")
    if not messages:
        print("[ENGINEER] No messages received.")
        return

    for msg in messages:
        idea = msg["payload"].get("idea", "")
        product_spec = msg["payload"].get("product_spec", {})

        print(f"[ENGINEER] Received task from CEO.")
        print(f"[ENGINEER] Building for idea: {idea[:60]}...")

        # 1. Generate HTML
        html_content = generate_html(idea, product_spec)

        # 2. Create GitHub issue
        issue_url = create_github_issue(idea, product_spec)

        # 3. Get base branch SHA
        base_sha, base_branch = get_main_branch_sha()

        # 4. Create branch
        branch_name = "agent-landing-page"
        create_branch(branch_name, base_sha)

        # 5. Commit HTML file
        commit_file(branch_name, html_content, idea)

        # 6. Get or create PR
        pr_url = get_or_create_pull_request(branch_name, base_branch, idea, issue_url)

        # 7. Send result back to CEO
        result_msg = bus.create_message(
            from_agent="engineer",
            to_agent="ceo",
            message_type="result",
            payload={
                "pr_url": pr_url or "PR creation failed",
                "issue_url": issue_url or "Issue creation failed",
                "branch": branch_name,
                "html_generated": True
            },
            parent_message_id=msg["message_id"]
        )
        bus.send(result_msg)
        print("[ENGINEER] Results sent to CEO.")